name: Ejecutar comando bash
on:
  workflow_dispatch:
    inputs:
      argumento1:
        description: 'comando a ejecutar'
        required: true
        default: 'echo "hola mundo"'
      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Ejecutar comandos en la consola bash
      run:  ${{ github.event.inputs.argumento1 }}"
       
