hname: comando
on:
  workflow_dispatch:
    inputs:
      argumento:
        description: 'comando a ejecutar'
        required: true
        default: echo "hola"'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Ejecutar comandos en la consola bash
      shell: bash
    - run: ${{ github.event.inputs.argumento }}"
       
