name: comando
on:
  workflow_dispatch:
    inputs:
      command:
        description: 'command to run'
        required: true
        default: echo hola

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Ejecutar comandos en la consola bash
      shell: bash
      run: ${{ github.event.inputs.argumento }}
       
