name: Expresiones
run-name: ¡Estoy aprendiendo a usar Expresiones!
on:
  workflow_dispatch:
    
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Correr script
        run: ping -c 4 8.8.8.8
  
