name: Crear nuevo repositorio
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Crear nuevo repositorio
      uses: actions/create-repo@v1
      with:
        name: Nuevo repositorio
        description: Este es un nuevo repositorio creado por un flujo de trabajo de GitHub.
